name: Default

on:
  push:
  pull_request:
    types: ['synchronize']

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install
        run: |
        npm install --global pnpm 
        pnpm install --prefer-offline
   
      - name: Check
        run: |
        pnpm run lint 
        pnpm run build
        pnpm run test
        continue-on-error: true
         
      - name: Annotate
        uses: agyemanjp/ci-checks-action@v2.1.1
        with:
          ghToken: "${{ secrets.GITHUB_TOKEN }}"
          checks: '[
              {
                "name": "lint",
                "fileName": ".lint.run.json",
                "prChangesOnly": true
              },
              {
                "name": "test",
                "fileName": ".test.run.json",
                "prChangesOnly": false
              }
            ]'
        
     