 name: Release
 
 on:
   push:
     branches:
       - master
 
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         id: release
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: standard
           pull-request-title-pattern: "PR${scope}: release${component} ${version}"

       - uses: actions/checkout@v2
         if: ${{ steps.release.outputs.release_created }}

       - uses: actions/setup-node@v1
         with:
           node-version: 16
           registry-url: 'https://registry.npmjs.org'
         if: ${{ steps.release.outputs.release_created }}

       - run: |
          npm install -g pnpm
          pnpm deps
         if: ${{ steps.release.outputs.release_created }}
         
       - run: |
          pnpm lint
          pnpm build
          pnpm pubstage
          cd dist
          npm publish
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
         if: ${{ steps.release.outputs.release_created }}